build: add `net-pop` dependency from `ruby` repo
We are experiencing some issues to deploy our changes, as the Docker
build step is failing with the following error:

```
 > [build 3/6] RUN bundle install &&     rm -rf ~/.bundle/ "/usr/local/bundle"/ruby/*/cache "/usr/local/bundle"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile:
14.33 Installing warden 1.2.9
14.34 Fetching rack-protection 4.0.0
14.35 Installing rack-protection 4.0.0
14.36 Fetching sprockets 4.2.0
14.38 Installing sprockets 4.2.0
14.41 Fetching websocket-driver 0.7.6
14.42 Installing websocket-driver 0.7.6 with native extensions
21.46 Downloading net-pop-0.1.2 revealed dependencies not in the API or the lockfile
21.46 (net-protocol (>= 0)).
21.46 Running `bundle update net-pop` should fix the problem.
------
Dockerfile:35
--------------------
  34 |     COPY Gemfile Gemfile.lock .ruby-version ./
  35 | >>> RUN bundle install && \
  36 | >>>     rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
  37 | >>>     bundle exec bootsnap precompile --gemfile
  38 |
--------------------
ERROR: failed to solve: process "/bin/sh -c bundle install &&     rm -rf ~/.bundle/ \"${BUNDLE_PATH}\"/ruby/*/cache \"${BUNDLE_PATH}\"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile" did not complete successfully: exit code: 34
```

After digging around for a bit it seems that the temporary solution
until we update to Ruby 3.3.4 is to add it from the ruby repo as a
dependency.